### ISSUE TITLE
planetgolang.com down?

### ISSUE THREAD

**Issue by AlekSi** [galdor/planetgolang#1]
Both http://planetgolang.com and https://planetgolang.com seems to be down at the moment.

**Comment by galdor** [comment]
On 2018-08-19 05:08, Alexey Palazhchenko wrote:
> Both http://planetgolang.com and https://planetgolang.com seems to be down at the moment.

Hi Alexey,

I stopped the website since it never really took off, and I lack the time
necessary to work on it. The code stays open source though.

Regards,

-- 
Nicolas Martyanoff
http://snowsyn.net
khaelin@gmail.com
